---
- name: Restart ssh
  service:
    name: "{{ ssh_service_name }}"
    state: restarted
  listen: restart sshd

- name: Reload sysctl
  command: sysctl --system
  listen: reload sysctl

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted
  listen: restart fail2ban
