---
- name: "Zero-Trust VPN | Preflight"
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: vps_hardening
      tags: [hardening]

- name: "Zero-Trust VPN | Orchestration"
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: vps_orchestration
      tags: [orchestration]
