---
- name: Restart docker
  service:
    name: docker
    state: restarted
  listen: restart docker

- name: Reload ufw
  command: ufw reload  # noqa: command-instead-of-module
  register: vps_orchestration_ufw_reload
  changed_when: "'Firewall reloaded' in (vps_orchestration_ufw_reload.stdout ~ vps_orchestration_ufw_reload.stderr)"
  listen: reload ufw
