---
- name: "AdGuard | Config | Generate password hash"
  set_fact:
    vault_adguard_password_hash: >-
      {{
        adguard_password | password_hash(
          'bcrypt',
          ((adguard_internal_domain ~ inventory_hostname) | hash('sha256'))[:22],
          ident='2y'
        )
      }}
  no_log: true
  changed_when: false
  when: adguard_password is defined
  tags: [adguard]

- name: "AdGuard | Config | Deploy AdGuardHome.yaml before containers start"
  template:
    src: AdGuardHome.yaml.j2
    dest: "{{ project_root }}/volumes/adguard/conf/AdGuardHome.yaml"
    backup: yes
    mode: '0600'
  no_log: true
  tags: [adguard]
