---
- name: "Volumes | Create | Caddy data and config directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ project_root }}/volumes/caddy/data"
    - "{{ project_root }}/volumes/caddy/config"
  tags: [volumes]

- name: "Volumes | Create | wg-easy directory"
  file:
    path: "{{ project_root }}/volumes/wg-easy"
    state: directory
    mode: '0755'
  tags: [volumes]

- name: "Volumes | Create | AdGuard directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ project_root }}/volumes/adguard/work"
    - "{{ project_root }}/volumes/adguard/conf"
  tags: [volumes]
