---
# Docker network
docker_network_subnet: "172.20.0.0/24"
adguard_container_ip: "172.20.0.2"
caddy_container_ip: "172.20.0.3"
wg_easy_container_ip: "172.20.0.4"
wg_easy_version: "15.3.0"

# UFW Docker script checksum (verifies script integrity)
ufw_docker_checksum: "sha256:643e56b080567c567b4aa28650196849b2a2da5dd0473fd3e5216b0886035ab0"
